export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  tagline: string;
  description: string;
  price: string; // USD price fallback
  priceBDT: string; // BDT price with ৳ sign
  originalPrice?: string;
  originalPriceBDT?: string;
  inStock: boolean;
  rating: number;
  image: string;
  badge?: string;
  popular?: boolean;
  featured?: boolean;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  slug: string;
  count: number;
}

export interface HeroSlide {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  imageUrl: string;
  linkUrl: string;
  buttonText: string;
  accentColor: string;
}

export const CATEGORIES: Category[] = [
  { id: "ai", name: "AI Tools", icon: "Bot", slug: "ai-tools", count: 24 },
  { id: "video", name: "Video Editing", icon: "Video", slug: "video-editing", count: 18 },
  { id: "design", name: "Design Tools", icon: "Palette", slug: "design-tools", count: 22 },
  { id: "writing", name: "Writing Tools", icon: "PenTool", slug: "writing-tools", count: 15 },
  { id: "vpn", name: "VPN & Security", icon: "Shield", slug: "vpn-security", count: 12 },
  { id: "streaming", name: "Streaming", icon: "Tv", slug: "streaming", count: 30 },
  { id: "microsoft", name: "Microsoft", icon: "AppWindow", slug: "microsoft", count: 16 },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: "slide-1",
    title: "ChatGPT Plus & Claude Pro Bundles",
    subtitle: "Unlock next-generation AI reasoning, high-speed responses, and priority access to GPT-4o & Claude 3.5 Sonnet.",
    badge: "🔥 TOP SELLER",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products?category=ai-tools",
    buttonText: "Explore AI Pass",
    accentColor: "from-purple-600 to-indigo-600",
  },
  {
    id: "slide-2",
    title: "Adobe Creative Cloud All Apps",
    subtitle: "Premiere Pro, Photoshop, After Effects, and Illustrator with 100GB Cloud Storage.",
    badge: "🎨 CREATIVE SPECIAL",
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products?category=design-tools",
    buttonText: "Get Adobe Access",
    accentColor: "from-red-600 to-pink-600",
  },
  {
    id: "slide-3",
    title: "Ultra-Fast VPN & Privacy Suite",
    subtitle: "Stream high-definition movies and protect all your devices with NordVPN & ExpressVPN Unlimited.",
    badge: "🛡️ ULTIMATE SECURITY",
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products?category=vpn-security",
    buttonText: "Activate Protection",
    accentColor: "from-blue-600 to-cyan-600",
  },
  {
    id: "slide-4",
    title: "Microsoft 365 Family & Windows 11 Pro",
    subtitle: "Official lifetime licenses & 1TB OneDrive cloud storage for all your office productivity needs.",
    badge: "💻 ESSENTIAL OFFICE",
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products?category=microsoft",
    buttonText: "View Microsoft Deals",
    accentColor: "from-sky-600 to-blue-700",
  },
  {
    id: "slide-5",
    title: "4K Premium Streaming Pass",
    subtitle: "Watch uninterrupted movies, series, and sports across TV, PC, tablet, and mobile devices.",
    badge: "🎬 POPULAR CHOICE",
    imageUrl: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products?category=streaming",
    buttonText: "Start Streaming",
    accentColor: "from-red-700 to-amber-600",
  },
];

export const ALL_PRODUCTS: Product[] = [
  // AI Tools
  {
    id: "prod-1",
    name: "ChatGPT Plus 1-Month Access",
    slug: "chatgpt-plus-1-month-access",
    category: "AI Tools",
    tagline: "GPT-4o, DALL-E 3 & Web Browsing",
    description: "Enjoy fast access to OpenAI's flagship models with custom GPTs and image creation.",
    price: "$9.99",
    priceBDT: "৳ 1,200",
    originalPrice: "$20.00",
    originalPriceBDT: "৳ 2,400",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=500&auto=format&fit=crop",
    badge: "🔥 HOT",
    popular: true,
  },
  {
    id: "prod-2",
    name: "Claude Pro Subscription",
    slug: "claude-pro-subscription",
    category: "AI Tools",
    tagline: "Anthropic Claude 3.5 Sonnet & Artifacts",
    description: "Superior code synthesis, reasoning, and document analysis with 5x usage limits.",
    price: "$11.49",
    priceBDT: "৳ 1,380",
    originalPrice: "$20.00",
    originalPriceBDT: "৳ 2,400",
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=500&auto=format&fit=crop",
    badge: "POPULAR",
    popular: true,
  },
  {
    id: "prod-3",
    name: "Midjourney Pro Membership",
    slug: "midjourney-pro-membership",
    category: "AI Tools",
    tagline: "Photorealistic AI Art & High-Res Upscaling",
    description: "Generate breathtaking commercial-grade artwork and concepts with fast GPU hours.",
    price: "$14.99",
    priceBDT: "৳ 1,800",
    originalPrice: "$30.00",
    originalPriceBDT: "৳ 3,600",
    inStock: false, // Out of stock example
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=500&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-4",
    name: "Perplexity Pro Yearly",
    slug: "perplexity-pro-yearly",
    category: "AI Tools",
    tagline: "AI Search Engine with Real-Time Web Data",
    description: "Pro search with GPT-4, Claude 3.5, Sonar Large, and file upload capabilities.",
    price: "$12.99",
    priceBDT: "৳ 1,550",
    originalPrice: "$25.00",
    originalPriceBDT: "৳ 3,000",
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=500&auto=format&fit=crop",
    popular: true,
  },
  {
    id: "prod-5",
    name: "GitHub Copilot Pro",
    slug: "github-copilot-pro",
    category: "AI Tools",
    tagline: "AI Pair Programmer for IDEs",
    description: "Auto-complete code, write unit tests, and resolve bugs directly inside VS Code and JetBrains.",
    price: "$7.99",
    priceBDT: "৳ 950",
    originalPrice: "$10.00",
    originalPriceBDT: "৳ 1,200",
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=500&auto=format&fit=crop",
    popular: true,
  },

  // Video Editing
  {
    id: "prod-6",
    name: "CapCut Pro Annual Pass",
    slug: "capcut-pro-annual-pass",
    category: "Video Editing",
    tagline: "AI Auto-Captions, Effects & 4K Export",
    description: "Popular video editor with advanced cloud visual effects, green screen, and text-to-speech.",
    price: "$6.99",
    priceBDT: "৳ 850",
    originalPrice: "$12.00",
    originalPriceBDT: "৳ 1,450",
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?q=80&w=500&auto=format&fit=crop",
    badge: "TRENDING",
  },
  {
    id: "prod-7",
    name: "Premiere Pro Standalone",
    slug: "premiere-pro-standalone",
    category: "Video Editing",
    tagline: "Industry-Standard Timeline Video Editing",
    description: "Professional video editing tool used by filmmakers, YouTubers, and commercial studios.",
    price: "$12.99",
    priceBDT: "৳ 1,550",
    originalPrice: "$23.00",
    originalPriceBDT: "৳ 2,750",
    inStock: false, // Out of stock example
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1536240478700-b869070f9279?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "prod-8",
    name: "DaVinci Resolve Studio Key",
    slug: "davinci-resolve-studio-key",
    category: "Video Editing",
    tagline: "Hollywood Color Grading & Fairlight Audio",
    description: "Lifetime key for DaVinci Resolve Studio with Fusion FX and Neural Engine acceleration.",
    price: "$29.99",
    priceBDT: "৳ 3,500",
    originalPrice: "$295.00",
    originalPriceBDT: "৳ 35,000",
    inStock: true,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "prod-9",
    name: "Descript Creator Pass",
    slug: "descript-creator-pass",
    category: "Video Editing",
    tagline: "Edit Video by Editing Text Script",
    description: "AI-powered podcast & video editor with Studio Sound, Overdub voice generation, and filler word removal.",
    price: "$8.99",
    priceBDT: "৳ 1,080",
    originalPrice: "$15.00",
    originalPriceBDT: "৳ 1,800",
    inStock: true,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=500&auto=format&fit=crop",
  },

  // Design Tools
  {
    id: "prod-10",
    name: "Canva Pro Team Invite",
    slug: "canva-pro-team-invite",
    category: "Design Tools",
    tagline: "Millions of Templates & Brand Kit",
    description: "Create social media graphics, presentations, vectors, and videos effortlessly.",
    price: "$4.99",
    priceBDT: "৳ 590",
    originalPrice: "$13.00",
    originalPriceBDT: "৳ 1,550",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=500&auto=format&fit=crop",
    badge: "BEST VALUE",
  },
  {
    id: "prod-11",
    name: "Figma Professional Plan",
    slug: "figma-professional-plan",
    category: "Design Tools",
    tagline: "Collaborative UI/UX & FigJam Boards",
    description: "Design mobile apps, websites, and design systems in real time with interactive prototypes.",
    price: "$9.99",
    priceBDT: "৳ 1,200",
    originalPrice: "$15.00",
    originalPriceBDT: "৳ 1,800",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "prod-12",
    name: "Freepik Premium Pass",
    slug: "freepik-premium-pass",
    category: "Design Tools",
    tagline: "Millions of Vectors, Photos & PSDs",
    description: "Unlimited downloads of premium graphics, icons, mockups, and AI image generator credits.",
    price: "$5.99",
    priceBDT: "৳ 720",
    originalPrice: "$12.00",
    originalPriceBDT: "৳ 1,450",
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1542744094-3a31727223ec?q=80&w=500&auto=format&fit=crop",
  },
  {
    id: "prod-13",
    name: "Envato Elements Unlimited",
    slug: "envato-elements-unlimited",
    category: "Design Tools",
    tagline: "Stock Video, Music, Graphic Templates",
    description: "Unlimited creative assets including video templates, audio tracks, 3D assets, and web themes.",
    price: "$11.99",
    priceBDT: "৳ 1,440",
    originalPrice: "$16.50",
    originalPriceBDT: "৳ 1,980",
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=500&auto=format&fit=crop",
  },

  // Writing Tools
  {
    id: "prod-14",
    name: "Grammarly Premium 1-Year",
    slug: "grammarly-premium-1-year",
    category: "Writing Tools",
    tagline: "Advanced Tone, Plagiarism & AI Rewrite",
    description: "Elevate your writing style, fix tone issues, and eliminate grammar mistakes in real time.",
    price: "$7.49",
    priceBDT: "৳ 900",
    originalPrice: "$12.00",
    originalPriceBDT: "৳ 1,450",
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=500&auto=format&fit=crop",
    badge: "ESSENTIAL",
  },
  {
    id: "prod-15",
    name: "QuillBot Premium Annual",
    slug: "quillbot-premium-annual",
    category: "Writing Tools",
    tagline: "Unlimited Paraphrasing & Summarizer",
    description: "Rewrite sentences, expand text, format citations, and check for duplicate content.",
    price: "$4.99",
    priceBDT: "৳ 600",
    originalPrice: "$9.95",
    originalPriceBDT: "৳ 1,200",
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=500&auto=format&fit=crop",
  },

  // VPN & Security
  {
    id: "prod-16",
    name: "NordVPN Ultimate 1-Year",
    slug: "nordvpn-ultimate-1-year",
    category: "VPN & Security",
    tagline: "Double Encryption & Threat Protection",
    description: "Secure up to 10 devices with high-speed global servers, malware shield, and ad blocker.",
    price: "$4.99",
    priceBDT: "৳ 600",
    originalPrice: "$12.99",
    originalPriceBDT: "৳ 1,550",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=500&auto=format&fit=crop",
    badge: "TOP SAFETY",
  },
  {
    id: "prod-17",
    name: "ExpressVPN Unlimited Key",
    slug: "expressvpn-unlimited-key",
    category: "VPN & Security",
    tagline: "Lightning Speeds across 94 Countries",
    description: "Stream region-locked content seamlessly with Lightway protocol and zero logs policy.",
    price: "$5.99",
    priceBDT: "৳ 720",
    originalPrice: "$12.95",
    originalPriceBDT: "৳ 1,550",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?q=80&w=500&auto=format&fit=crop",
  },

  // Streaming
  {
    id: "prod-18",
    name: "Netflix 4K Ultra HD Pass",
    slug: "netflix-4k-ultra-hd-pass",
    category: "Streaming",
    tagline: "4 Screens, Spatial Audio & No Ads",
    description: "Watch latest blockbuster movies and original series in crisp 4K HDR quality.",
    price: "$5.49",
    priceBDT: "৳ 660",
    originalPrice: "$22.99",
    originalPriceBDT: "৳ 2,750",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?q=80&w=500&auto=format&fit=crop",
    badge: "MUST HAVE",
  },
  {
    id: "prod-19",
    name: "Prime Video Premium",
    slug: "prime-video-premium",
    category: "Streaming",
    tagline: "Exclusive Movies, Sports & TV Shows",
    description: "Stream Amazon Originals, live sports events, and award-winning international cinema.",
    price: "$3.99",
    priceBDT: "৳ 480",
    originalPrice: "$14.99",
    originalPriceBDT: "৳ 1,800",
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?q=80&w=500&auto=format&fit=crop",
  },

  // Microsoft
  {
    id: "prod-20",
    name: "Microsoft 365 Personal",
    slug: "microsoft-365-personal",
    category: "Microsoft",
    tagline: "Word, Excel, PowerPoint & 1TB OneDrive",
    description: "Full suite of office apps for PC, Mac, iPad, and smartphone with cloud backup.",
    price: "$9.99",
    priceBDT: "৳ 1,200",
    originalPrice: "$69.99",
    originalPriceBDT: "৳ 8,400",
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=500&auto=format&fit=crop",
    badge: "OFFICIAL",
  },
  {
    id: "prod-21",
    name: "Windows 11 Pro Activation Key",
    slug: "windows-11-pro-activation-key",
    category: "Microsoft",
    tagline: "Lifetime Retail Key with Digital License",
    description: "Activate Windows 11 Pro instantly with official updates, BitLocker, and Remote Desktop.",
    price: "$8.99",
    priceBDT: "৳ 1,080",
    originalPrice: "$199.00",
    originalPriceBDT: "৳ 23,800",
    inStock: true,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1618401471353-b98aedd04e11?q=80&w=500&auto=format&fit=crop",
  },
];
